services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgress_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - pgnetwork
    
  # app:
  #   build: .
  #   restart: always
  #   depends_on:
  #     - pgdatabase

volumes:
  ny_taxi_postgress_data:
  pgadmin-data:

networks:
  pgnetwork:
    name: pgnetwork
    driver: bridge